// 三崎屋電工AI — 初期シードデータ
// 全て localStorage に永続化される。「管理メニュー → データをリセット」で再seed

window.SEED = {
  tenant: { id: 'misakiya', name: '三崎屋電工', established: '1982' },

  users: [
    { id: 'u1', name: '三崎 太郎', role: '管理者', title: '代表取締役', initials: 'MT', avatarClass: '' },
    { id: 'u2', name: '佐藤 次郎', role: '現場責任者', title: '第一種電気工事士', initials: 'SJ', avatarClass: 'b' },
    { id: 'u3', name: '山田 花子', role: '若手技術者', title: '第二種電気工事士 (取得3年)', initials: 'YH', avatarClass: 'c' },
    { id: 'u4', name: '鈴木 一馬', role: '見習い', title: '2024年入社', initials: 'SK', avatarClass: 'd' },
  ],

  categories: [
    { id: 'panel', name: '分電盤・盤類', color: '#3b82f6' },
    { id: 'hv', name: '高圧設備', color: '#ef4444' },
    { id: 'cable', name: 'ケーブル・幹線', color: '#f59e0b' },
    { id: 'lighting', name: '照明・弱電', color: '#8b5cf6' },
    { id: 'safety', name: '測定・安全', color: '#10b981' },
    { id: 'ground', name: '接地・避雷', color: '#06b6d4' },
  ],

  works: [
    {
      id: 'w1', title: '分電盤の交換', category: 'panel', tags: ['分電盤', '交換', 'ブレーカー'],
      site: '◯◯工場', difficulty: 3, duration: '約 4時間',
      thumb: 'panel',
      status: 'published', author: 'u1', approver: 'u2',
      createdAt: '2024-04-10', updatedAt: '2024-05-20',
      views: 84, description: '既設の分電盤を安全に取り外し、新しい分電盤を取り付ける作業。',
      steps: [
        { title: '停電確認', desc: 'ブレーカーをOFFにし、停電していることを主幹の一次側・二次側の両方で確認する。', note: '' },
        { title: '検電', desc: '検電器で各相の電圧がないことを確認する。検電器は事前に既知の生きた回路で動作確認しておく。', note: '検電器の動作確認を怠らない (故障検電器での「停電」誤認は感電事故の主因)' },
        { title: '養生', desc: '周囲を養生し、作業スペースを確保する。落下物対策のブルーシートを盤下に敷く。', note: '' },
        { title: '既設分電盤の取外し', desc: '配線に符号を付けてから外し、既設分電盤を取り外す。写真を撮ってから外すと復旧時に確実。', note: '' },
        { title: '新設分電盤の取付', desc: '水平・垂直を水準器で確認し、アンカーで固定する。取付ボルトは規定トルクで締める。', note: '' },
        { title: '配線復旧', desc: '符号に従って配線を接続する。端子ネジは規定トルク (M4=1.2N·m 目安) で締付。', note: '' },
        { title: '絶縁抵抗測定', desc: '500Vメガーで各回路の絶縁抵抗を測定。0.1MΩ以上を確認。', note: '' },
        { title: '通電・動作確認', desc: '主幹→分岐の順で投入し、各回路の動作を確認する。', note: '' },
      ],
      tools: [
        { name: '検電器 (低圧用)', qty: '1' },
        { name: '絶縁抵抗計 (メガー)', qty: '1' },
        { name: 'トルクドライバー', qty: '1' },
        { name: '水準器', qty: '1' },
        { name: '養生シート', qty: '2枚' },
        { name: '圧着工具 (リングスリーブ)', qty: '1' },
      ],
      materials: [
        { name: '分電盤 (指定品番)', qty: '1台' },
        { name: 'IV電線 5.5sq', qty: '10m' },
        { name: 'リングスリーブ 中', qty: '20個' },
      ],
      tips: [
        '配線を外す前に必ず写真撮影 (最低3方向)。復旧時のトラブルを予防できる。',
        '端子ネジは規定トルクで締める。締めすぎは端子破損、緩みは発熱の原因。',
        'ブレーカーの動作テストは通電前に必ず行う (ボタン押下で正常にトリップするか)。',
      ],
      cautions: [
        '停電作業でも一次側は活線。触れないこと。',
        '高所作業になる場合は必ず二人組で。',
      ],
      resources: [
        { type: 'pdf', name: '単線結線図', meta: 'PDF · 1.2MB', url: '' },
        { type: 'pdf', name: '施工図', meta: 'PDF · 3.4MB', url: '' },
        { type: 'img', name: '現場写真一覧', meta: '12枚', url: '' },
      ],
      relatedIds: ['w2', 'w7', 'w11'],
      videoUrl: '',
      history: [
        { time: '05/20', who: '三崎 太郎', what: '手順書を公開しました' },
        { time: '05/18', who: '佐藤 次郎', what: '承認しました' },
        { time: '05/17', who: '三崎 太郎', what: '手順6-8を追加' },
        { time: '04/10', who: '三崎 太郎', what: '手順書を新規作成' },
      ],
    },
    {
      id: 'w2', title: '低圧ブレーカーの交換', category: 'panel', tags: ['ブレーカー', '交換'],
      site: '◯◯商業ビル', difficulty: 2, duration: '約 1時間',
      thumb: 'breaker', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-04-15', updatedAt: '2024-05-19', views: 62,
      description: '既設ブレーカーを取り外し、同容量のブレーカーに交換する作業。',
      steps: [
        { title: '該当ブレーカーOFF', desc: '交換対象のブレーカーを OFF にする。', note: '' },
        { title: '主幹OFF・検電', desc: '主幹ブレーカーもOFFにし、検電器で確認。', note: '' },
        { title: '既設ブレーカー取外し', desc: '配線を外し、既設ブレーカーを取り外す。', note: '' },
        { title: '新設ブレーカー取付', desc: '同容量・同メーカー品の新ブレーカーを取り付ける。', note: '端子ネジ規定トルク厳守' },
        { title: '通電確認', desc: '主幹→分岐の順に投入し、負荷側の動作を確認。', note: '' },
      ],
      tools: [{ name: '検電器', qty: '1' }, { name: 'トルクドライバー', qty: '1' }],
      materials: [{ name: 'ブレーカー (30A / 2P1E)', qty: '1個' }],
      tips: ['既設ブレーカーの容量・極数を必ず控えてから発注。'],
      cautions: ['過去の焼損跡がある場合は原因調査が先。'],
      resources: [{ type: 'pdf', name: 'ブレーカー選定表', meta: 'PDF · 800KB', url: '' }],
      relatedIds: ['w1', 'w11'],
      videoUrl: '',
      history: [{ time: '05/19', who: '佐藤 次郎', what: '手順書を更新' }],
    },
    {
      id: 'w3', title: '照明器具の取付', category: 'lighting', tags: ['照明', 'LED', '取付'],
      site: '◯◯オフィス', difficulty: 1, duration: '約 30分/台',
      thumb: 'light', status: 'published', author: 'u3', approver: 'u2',
      createdAt: '2024-03-20', updatedAt: '2024-05-18', views: 48,
      description: '天井への LED 照明器具の取付作業。',
      steps: [
        { title: '停電確認・検電', desc: '該当回路を OFF にし検電。', note: '' },
        { title: '既設照明の撤去', desc: '既設器具を取り外す。安定器は分別廃棄。', note: '水銀含有安定器は特別管理産業廃棄物' },
        { title: '結線', desc: '差込コネクタで結線 (電源側・器具側の極性確認)。', note: '' },
        { title: '器具取付・動作確認', desc: '器具を天井にビス留めし、通電確認。', note: '' },
      ],
      tools: [{ name: '脚立', qty: '1' }, { name: '差込コネクタ工具', qty: '1' }],
      materials: [{ name: 'LEDベースライト 40W形', qty: '1台' }, { name: '差込コネクタ 2P', qty: '2個' }],
      tips: ['複数台を交換する場合は 1台完了させて動作確認 → 残り着手 の順で。'],
      cautions: ['脚立作業は必ず二人組 (支え役)。'],
      resources: [],
      relatedIds: [],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w4', title: 'CVケーブル端末処理', category: 'cable', tags: ['CV', '端末処理', 'ケーブル'],
      site: '◯◯変電所', difficulty: 4, duration: '約 2時間/箇所',
      thumb: 'cable', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-02-10', updatedAt: '2024-05-15', views: 71,
      description: '高圧 CV ケーブルの屋内終端処理 (テープ巻き / ゴムストレスコーン)。',
      steps: [
        { title: 'ケーブル切断・清掃', desc: '所定寸法で切断し、シースを丁寧に剥離。', note: '' },
        { title: '半導電層の剥離', desc: '半導電層を規定寸法で剥離。カッター跡は導電絶縁テープで補修。', note: 'カッター傷は絶縁破壊の起点になる。目視でチェック。' },
        { title: 'ストレスコーン装着', desc: 'ストレスコーンを規定位置に装着。潤滑剤は指定品のみ使用。', note: '' },
        { title: '圧着端子取付', desc: '芯線に圧着端子を取り付ける (油圧圧着工具・規定ダイス)。', note: '' },
        { title: '絶縁テープ処理', desc: '自己融着テープ → 保護テープの順で規定重ね幅で巻く。', note: '' },
      ],
      tools: [{ name: '半導電層剥離工具', qty: '1' }, { name: '油圧圧着工具', qty: '1' }, { name: '自己融着テープ', qty: '2巻' }],
      materials: [{ name: 'ストレスコーン (相当品)', qty: '3個' }, { name: '圧着端子 (60sq)', qty: '3個' }],
      tips: ['雨天時は絶対に施工しない (吸湿でトラッキング事故)。', '施工写真を必ず残す (半導電層剥離部・圧着後・完成後)。'],
      cautions: ['高圧設備。誤結線は爆発事故につながる。'],
      resources: [{ type: 'pdf', name: 'CV端末施工要領書', meta: 'PDF · 4.2MB', url: '' }],
      relatedIds: ['w5'],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w5', title: '絶縁抵抗測定の実演', category: 'safety', tags: ['絶縁抵抗', '測定', 'メガー'],
      site: '社内訓練用', difficulty: 1, duration: '約 15分',
      thumb: 'meter', status: 'published', author: 'u1', approver: 'u1',
      createdAt: '2024-01-05', updatedAt: '2024-05-12', views: 105,
      description: 'メガー (絶縁抵抗計) を使った絶縁抵抗測定の実演。新人向け。',
      steps: [
        { title: 'メガーの動作確認', desc: 'L と E をショートで 0MΩ、開放で ∞ を確認。', note: '' },
        { title: '対象回路の電源切', desc: '電源を切り、負荷側の機器も外す (誤測定防止)。', note: '' },
        { title: '測定', desc: '電線間・電線対地間で測定 (100V回路=500Vレンジ)。', note: '' },
        { title: '判定', desc: '電技解釈14条: 対地電圧150V以下=0.1MΩ以上、150V超300V以下=0.2MΩ以上、300V超=0.4MΩ以上。', note: '' },
        { title: '記録', desc: '測定値・日時・測定者を記録票に残す。', note: '' },
      ],
      tools: [{ name: '絶縁抵抗計 500V', qty: '1' }],
      materials: [],
      tips: ['測定前に必ずメガーの電池残量を確認。'],
      cautions: ['ケーブル残留電荷に注意。測定後は必ず接地放電。'],
      resources: [{ type: 'pdf', name: '絶縁抵抗判定基準表', meta: 'PDF · 340KB', url: '' }],
      relatedIds: ['w1'],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w6', title: 'PASの交換', category: 'hv', tags: ['PAS', '高圧', '交換'],
      site: '◯◯工場', difficulty: 5, duration: '約 8時間 (停電作業)',
      thumb: 'pas', status: 'published', author: 'u1', approver: 'u2',
      createdAt: '2024-02-15', updatedAt: '2024-05-10', views: 43,
      description: '柱上気中開閉器 (PAS) の交換作業。電力会社との停電調整が必須。',
      steps: [
        { title: '電力会社との調整', desc: '停電範囲・時間を電力会社と事前調整。', note: '' },
        { title: '停電・検電・接地', desc: '停電手続きの三種の神器: 停電→検電→接地 の順で必ず。', note: '接地忘れは死亡事故の主因。省略絶対NG' },
        { title: '既設PAS取外し', desc: '高所作業車で既設PASを取り外す。', note: '' },
        { title: '新設PAS取付', desc: '規定寸法で取り付け。制御ケーブルの配線間違いに注意。', note: '' },
        { title: '動作試験', desc: 'SOG動作試験、地絡試験を実施。', note: '' },
        { title: '接地撤去・送電', desc: '接地を撤去し、電力会社と連絡して送電。', note: '' },
      ],
      tools: [{ name: '高所作業車', qty: '1' }, { name: '接地器具', qty: '1式' }, { name: '検電器 (高圧用)', qty: '1' }],
      materials: [{ name: 'PAS (SOG制御方式)', qty: '1' }],
      tips: ['SOG制御ケーブルの結線は特に慎重に (誤結線で不動作 = 波及事故)。'],
      cautions: ['高圧活線に絶対に触れない。停電・検電・接地の三点セット必須。', '波及事故 = 会社倒産級の損害。'],
      resources: [{ type: 'pdf', name: 'PAS取扱説明書', meta: 'PDF · 8.1MB', url: '' }, { type: 'dwg', name: 'SOG結線図', meta: 'PDF · 1.4MB', url: '' }],
      relatedIds: ['w7'],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w7', title: '高圧受変電設備の更新', category: 'hv', tags: ['受変電', 'キュービクル', '更新'],
      site: '◯◯物流センター', difficulty: 5, duration: '約 2日 (停電作業)',
      thumb: 'cubicle', status: 'published', author: 'u1', approver: 'u2',
      createdAt: '2024-01-20', updatedAt: '2024-05-18', views: 38,
      description: 'キュービクル式高圧受電設備の更新工事。設計〜引渡しまで。',
      steps: [
        { title: '事前調査・設計', desc: '既設容量・レイアウト・需要予測から新設仕様を決定。', note: '' },
        { title: '電力会社協議', desc: '受電契約・停電日程を調整。', note: '' },
        { title: '既設撤去', desc: '停電後、既設キュービクルを撤去。搬出経路の事前確認必須。', note: '' },
        { title: '新設据付', desc: '基礎ボルトで固定。水平調整。', note: '' },
        { title: '結線・試験', desc: '一次二次配線、内部試験、耐圧試験を実施。', note: '' },
        { title: '送電・引渡し', desc: '関係官庁への届出、需要家への操作説明。', note: '' },
      ],
      tools: [{ name: 'クレーン', qty: '1' }, { name: '耐圧試験機', qty: '1' }],
      materials: [{ name: 'キュービクル (JIS標準)', qty: '1台' }],
      tips: ['既設更新は搬出経路が最大の課題。事前図面照合を徹底。'],
      cautions: ['高圧設備。有資格者のみ触れる。'],
      resources: [],
      relatedIds: ['w6', 'w8'],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w8', title: '幹線ケーブルラック敷設', category: 'cable', tags: ['ラック', '幹線', '敷設'],
      site: '◯◯工場 増設', difficulty: 3, duration: '約 3日',
      thumb: 'rack', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-03-01', updatedAt: '2024-05-15', views: 29,
      description: 'ケーブルラックの新設と幹線ケーブルの敷設。',
      steps: [
        { title: '経路確認・墨出し', desc: '設計図と現地を照合し、経路に墨出し。', note: '梁・ダクトとの干渉確認必須' },
        { title: '支持金物取付', desc: '3m ピッチで支持金物を取付。', note: '' },
        { title: 'ラック取付', desc: 'ラックを支持金物に固定。曲り部はエルボ使用。', note: '' },
        { title: 'ケーブル敷設', desc: '延線ローラー使用。曲げ半径は径の8倍以上。', note: '' },
        { title: 'ケーブル固定', desc: '2m ピッチでケーブルバンド固定。', note: '' },
      ],
      tools: [{ name: '延線ローラー', qty: '10個' }, { name: 'ケーブルグリップ', qty: '2個' }],
      materials: [{ name: 'ケーブルラック 600mm幅', qty: '30m' }, { name: 'CVT 60sq', qty: '35m' }],
      tips: [],
      cautions: ['天井裏作業は熱中症に注意。'],
      resources: [],
      relatedIds: [],
      videoUrl: '',
      history: [],
    },
    {
      id: 'w9', title: '高圧分電盤の交換', category: 'panel', tags: ['分電盤', '高圧', '交換'],
      site: '◯◯病院', difficulty: 4, duration: '約 6時間',
      thumb: 'hv-panel', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-04-22', updatedAt: '2024-04-22', views: 21,
      description: '高圧分電盤の交換工事。', steps: [], tools: [], materials: [],
      tips: [], cautions: [], resources: [], relatedIds: ['w1'], videoUrl: '', history: [],
    },
    {
      id: 'w10', title: '動力分電盤の交換', category: 'panel', tags: ['動力盤', '3相', '交換'],
      site: '◯◯学校', difficulty: 3, duration: '約 4時間',
      thumb: 'power-panel', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-03-15', updatedAt: '2024-03-15', views: 17,
      description: '3相動力分電盤の交換。', steps: [], tools: [], materials: [],
      tips: [], cautions: [], resources: [], relatedIds: ['w1'], videoUrl: '', history: [],
    },
    {
      id: 'w11', title: '漏電遮断器の取付', category: 'safety', tags: ['漏電', 'ELB', '取付'],
      site: '◯◯マンション', difficulty: 2, duration: '約 45分',
      thumb: 'elb', status: 'published', author: 'u3', approver: 'u2',
      createdAt: '2024-04-01', updatedAt: '2024-04-30', views: 33,
      description: '漏電遮断器 (ELB) の新規取付。既設ブレーカーからの交換。',
      steps: [
        { title: '停電・検電', desc: '', note: '' },
        { title: '既設取外し', desc: '', note: '' },
        { title: 'ELB取付・結線', desc: '一次側・二次側の極性を厳守。', note: '' },
        { title: '動作テスト', desc: 'テストボタンでトリップ動作確認。', note: '' },
      ],
      tools: [], materials: [{ name: 'ELB 30A 30mA', qty: '1' }],
      tips: [], cautions: [], resources: [], relatedIds: ['w1', 'w2'], videoUrl: '', history: [],
    },
    {
      id: 'w12', title: '接地工事 (D種)', category: 'ground', tags: ['接地', 'アース', 'D種'],
      site: '◯◯倉庫 新設', difficulty: 2, duration: '約 3時間',
      thumb: 'ground', status: 'published', author: 'u2', approver: 'u1',
      createdAt: '2024-02-05', updatedAt: '2024-04-20', views: 25,
      description: '低圧機器の D種接地工事。100Ω以下を確保。',
      steps: [
        { title: '接地極打込み', desc: '深さ 750mm 以上に接地棒を打込む。', note: '' },
        { title: '接地線接続', desc: '接地棒と機器間を接地線で接続。', note: '' },
        { title: '接地抵抗測定', desc: '接地抵抗計で 100Ω以下を確認。', note: '' },
      ],
      tools: [{ name: '接地抵抗計', qty: '1' }, { name: 'ハンマー', qty: '1' }],
      materials: [{ name: '接地棒 φ14×1500mm', qty: '1本' }, { name: '緑IV 5.5sq', qty: '2m' }],
      tips: ['接地抵抗値は季節・湿度で変動。乾燥期の測定値で基準確認。'],
      cautions: [],
      resources: [],
      relatedIds: [], videoUrl: '', history: [],
    },
    // 承認待ち
    {
      id: 'w13', title: '照明制御盤の増設', category: 'panel', tags: ['制御盤', '照明', '増設'],
      site: '◯◯ホール', difficulty: 3, duration: '約 5時間',
      thumb: 'ctrl-panel', status: 'pending', author: 'u3', approver: 'u2',
      createdAt: '2024-05-25', updatedAt: '2024-05-25', views: 3,
      description: '調光機能付き照明制御盤の増設 (承認待ち)。', steps: [
        { title: '既設盤の空きスペース確認', desc: '', note: '' },
        { title: '制御盤本体の取付', desc: '', note: '' },
        { title: 'DMX制御ケーブル配線', desc: '', note: '' },
      ], tools: [], materials: [], tips: [], cautions: [], resources: [], relatedIds: [], videoUrl: '', history: [],
    },
    {
      id: 'w14', title: 'スマートメーターの取付', category: 'panel', tags: ['スマートメーター', '計量'],
      site: '◯◯戸建て', difficulty: 2, duration: '約 30分',
      thumb: 'meter2', status: 'pending', author: 'u3', approver: 'u1',
      createdAt: '2024-05-26', updatedAt: '2024-05-26', views: 1,
      description: 'スマートメーターへの取替 (承認待ち)。', steps: [
        { title: '需要家への挨拶・説明', desc: '', note: '' },
        { title: '停電作業許可', desc: '', note: '' },
        { title: '既設メーター取外し', desc: '', note: '' },
      ], tools: [], materials: [], tips: [], cautions: [], resources: [], relatedIds: [], videoUrl: '', history: [],
    },
  ],

  courses: [
    {
      id: 'c1', name: '電気工事 基礎コース', level: '初心者向け', badge: 'basic',
      description: '電気工事士として最初に学ぶべき基本作業を体系的に学ぶ。',
      chapters: [
        { title: '第1章 · 現場の安全ルール', workId: null, duration: 20 },
        { title: '第2章 · 停電・検電・接地', workId: 'w5', duration: 30 },
        { title: '第3章 · 絶縁抵抗測定', workId: 'w5', duration: 25 },
        { title: '第4章 · 照明器具の取付', workId: 'w3', duration: 25 },
        { title: '第5章 · 低圧ブレーカーの交換', workId: 'w2', duration: 30 },
        { title: '第6章 · 漏電遮断器の取付', workId: 'w11', duration: 25 },
        { title: '第7章 · 接地工事の基本', workId: 'w12', duration: 30 },
        { title: '第8章 · 分電盤の構造', workId: null, duration: 30 },
        { title: '第9章 · 分電盤の交換', workId: 'w1', duration: 45 },
        { title: '第10章 · ケーブルの選定', workId: null, duration: 25 },
        { title: '第11章 · 現場報告書の書き方', workId: null, duration: 20 },
        { title: '第12章 · 総合演習 (E-learning)', workId: null, duration: 40 },
      ],
    },
    {
      id: 'c2', name: '高圧設備 保守コース', level: '中級者向け', badge: 'mid',
      description: '第一種電気工事士向け。高圧設備の日常点検と保守作業。',
      chapters: [
        { title: '第1章 · 高圧設備の全体像', workId: null, duration: 30 },
        { title: '第2章 · キュービクルの構造', workId: 'w7', duration: 40 },
        { title: '第3章 · PAS の役割と点検', workId: 'w6', duration: 40 },
        { title: '第4章 · 高圧CVケーブル', workId: 'w4', duration: 45 },
        { title: '第5章 · 保安点検の実務', workId: null, duration: 35 },
        { title: '第6章 · 波及事故防止', workId: null, duration: 30 },
        { title: '第7章 · 高圧分電盤', workId: 'w9', duration: 35 },
        { title: '第8章 · 総合試験', workId: null, duration: 30 },
      ],
    },
    {
      id: 'c3', name: '受変電設備 施工コース', level: '上級者向け', badge: 'adv',
      description: 'キュービクル新設工事の全プロセス。',
      chapters: [
        { title: '第1章 · 設計基準', workId: null, duration: 45 },
        { title: '第2章 · 電力会社協議', workId: null, duration: 30 },
        { title: '第3章 · 基礎工事', workId: null, duration: 40 },
        { title: '第4章 · 据付工事', workId: 'w7', duration: 60 },
        { title: '第5章 · 一次側配線', workId: null, duration: 45 },
        { title: '第6章 · 幹線敷設', workId: 'w8', duration: 60 },
        { title: '第7章 · 内部試験', workId: null, duration: 45 },
        { title: '第8章 · 耐圧試験', workId: null, duration: 45 },
        { title: '第9章 · 官庁届出', workId: null, duration: 30 },
        { title: '第10章 · 引渡し実務', workId: null, duration: 40 },
      ],
    },
  ],

  // workId ごとの理解度テスト (3-5問)
  quizzes: {
    w1: [
      { q: '分電盤交換の作業開始前、最初に必ず行うべきことは?', choices: ['配線に符号を付ける', 'ブレーカーOFF後の検電確認', '新設盤の水平確認', '養生シートを敷く'], answer: 1, explain: '検電による停電確認は感電防止の最重要工程。配線符号や養生は検電後。' },
      { q: '検電器を使う前に必ず行うべきことは?', choices: ['電池残量の確認', '端子カバーを外す', '既知の生きた回路で動作確認', '手袋を外して感度確認'], answer: 2, explain: '故障検電器で「停電」と誤認する感電事故が多発。既知の活線で動作確認してから使う。' },
      { q: '端子ネジの締付で正しいのは?', choices: ['できるだけ強く締める', '規定トルクで締める', '手で回らなくなるまで', '感覚で最適に'], answer: 1, explain: '締めすぎは端子破損、緩みは発熱の原因。規定トルク厳守。' },
      { q: '絶縁抵抗測定の合格基準 (100V回路 対地電圧150V以下) は?', choices: ['0.1MΩ以上', '0.4MΩ以上', '1MΩ以上', '100MΩ以上'], answer: 0, explain: '電技解釈14条: 150V以下=0.1MΩ以上、150V超300V以下=0.2MΩ以上。' },
      { q: '通電時のブレーカー投入順序は?', choices: ['分岐→主幹', '主幹→分岐', '同時にON', '任意で可'], answer: 1, explain: '主幹→分岐の順が原則。逆にすると突入電流が集中し主幹がトリップすることがある。' },
    ],
    w5: [
      { q: 'メガーの動作確認方法として正しいのは?', choices: ['ボタンを長押しする', 'LとEをショートで0MΩ、開放で∞', '内部電池を交換する', 'テスターで電圧を測る'], answer: 1, explain: 'LとEをショート/開放で 0/∞ を確認するのがメガーの動作確認。' },
      { q: '100V回路 (対地電圧150V以下) の絶縁抵抗合格基準は?', choices: ['0.1MΩ以上', '0.4MΩ以上', '1MΩ以上', '10MΩ以上'], answer: 0, explain: '電技解釈14条: 対地電圧150V以下は 0.1MΩ以上。' },
      { q: '測定時、負荷側の機器を外す理由は?', choices: ['見やすくするため', '誤測定を防ぐため', '機器を保護するため', '慣習として'], answer: 1, explain: '負荷側の機器が入っていると絶縁抵抗値が正しく測れない。誤測定を防ぐため。' },
      { q: '測定後に必ずすべきことは?', choices: ['メガー電池を抜く', '記録票に記入', '接地放電', '電源をON'], answer: 2, explain: 'ケーブル残留電荷は感電原因。測定後は必ず接地放電。' },
    ],
    w2: [
      { q: 'ブレーカー交換の最初の手順は?', choices: ['主幹OFF', '該当ブレーカーOFF', '検電', '既設取外し'], answer: 1, explain: '該当ブレーカーをまずOFFにしてから、主幹もOFFにして検電の順。' },
      { q: '既設と同容量・同メーカーを選ぶ理由は?', choices: ['安いから', '取付穴・端子形状が同じで確実', '見た目が揃うから', '在庫があるから'], answer: 1, explain: '取付穴・端子形状が同じで確実に取付できる。異メーカーは加工が必要になる。' },
      { q: '焼損跡があるブレーカーで最も注意すべきは?', choices: ['見た目', '交換前に原因調査', 'すぐ廃棄', '塗装補修'], answer: 1, explain: '過負荷/接触不良/漏電 など原因があるはず。原因を潰さないと再発する。' },
    ],
    w4: [
      { q: 'CV端末処理で最も重要なのは?', choices: ['見た目', '半導電層のカッター跡を残さない', 'テープの色', 'ストレスコーンの向き'], answer: 1, explain: 'カッター跡は絶縁破壊の起点になる。目視で必ずチェック。' },
      { q: '施工不可の天候は?', choices: ['曇り', '雨天', '晴天', '無風'], answer: 1, explain: '雨天施工は吸湿でトラッキング事故の原因。絶対不可。' },
      { q: '施工写真で最も重要なのは?', choices: ['作業員の顔', '半導電層剥離部/圧着後/完成後', '工具の集合写真', '天気'], answer: 1, explain: '不良発生時の原因究明に必要。剥離・圧着・完成の3点は必須。' },
    ],
    w6: [
      { q: 'PAS交換で「停電・検電・接地」を省略した場合の主な事故は?', choices: ['機器破損', '感電死亡事故', '停電時間延長', '見積超過'], answer: 1, explain: '接地忘れは死亡事故の主因。三種の神器は絶対省略しない。' },
      { q: 'SOG制御ケーブルの誤結線がもたらす最悪の結果は?', choices: ['作業やり直し', '波及事故 (他需要家停電)', '配線損傷', 'ブレーカートリップ'], answer: 1, explain: '波及事故は電力会社への損害賠償になり、会社倒産級のリスク。' },
      { q: '電力会社との事前調整で最も重要な項目は?', choices: ['停電範囲・時間', '担当者の名前', '交通経路', '弁当の手配'], answer: 0, explain: '停電範囲・時間の合意が全ての起点。ずれると波及事故になる。' },
    ],
    w11: [
      { q: 'ELB (漏電遮断器) の動作テストは?', choices: ['負荷を接続する', 'テストボタンでトリップ確認', 'メガーで測定', '電圧を測る'], answer: 1, explain: 'テストボタン押下でトリップすれば正常。動作しない ELB は交換。' },
      { q: 'ELB取付時の極性の重要性は?', choices: ['見た目', '誤動作/不動作の原因', '端子形状の問題', '関係ない'], answer: 1, explain: '一次側・二次側を逆にすると誤動作/不動作の原因。銘板の指示厳守。' },
    ],
    w12: [
      { q: 'D種接地の抵抗値基準は?', choices: ['10Ω以下', '100Ω以下', '500Ω以下', '1000Ω以下'], answer: 1, explain: 'D種は 100Ω以下。地絡時の感電を防ぐ最低基準。' },
      { q: '接地抵抗が季節で変わる主因は?', choices: ['気温変化', '土壌の湿度', '通行量', '磁場変化'], answer: 1, explain: '土壌の湿度で抵抗値が変わる。乾燥期の測定値で基準確認するのが安全。' },
    ],
  },

  notices: [
    { id: 'n1', type: 'new', title: '新しい手順書が公開されました (分電盤の交換)', body: '2024/05/20 付で「分電盤の交換」の手順書 v1.2 が公開されました。手順6-8が追加されています。', workId: 'w1', createdAt: '2024-05-20' },
    { id: 'n2', type: 'warn', title: '安全ポイント集を更新しました', body: '高所作業・活線作業の安全ルールを最新の労安則に合わせて更新しました。全員必読。', workId: null, createdAt: '2024-05-18' },
    { id: 'n3', type: 'info', title: '社内勉強会のお知らせ (高圧設備の保守)', body: '6/15 (土) 10:00 - 12:00、本社会議室にて。参加希望者は佐藤まで。', workId: null, createdAt: '2024-05-10' },
    { id: 'n4', type: 'info', title: '6月シフト希望の提出期限は 5/28 まで', body: '希望日程を Google スプレッドシートに記入してください。', workId: null, createdAt: '2024-05-08' },
    { id: 'n5', type: 'warn', title: '梅雨期の CV端末処理は原則見合わせ', body: '梅雨入り後は雨天施工となり事故リスクが高いため、CV端末処理は6/1-7/15 は原則見合わせとします。', workId: 'w4', createdAt: '2024-05-05' },
  ],

  // ユーザーごとのお気に入り workId 配列
  favorites: {
    u1: ['w1', 'w6', 'w4'],
    u2: ['w1', 'w2', 'w11'],
    u3: ['w3', 'w5', 'w11'],
    u4: [],
  },

  // ユーザーごとの最近の閲覧 [{workId, ts}]
  recent: {
    u1: [
      { workId: 'w1', ts: Date.now() - 1000 * 60 * 60 * 2 },
      { workId: 'w2', ts: Date.now() - 1000 * 60 * 60 * 5 },
      { workId: 'w4', ts: Date.now() - 1000 * 60 * 60 * 24 },
      { workId: 'w5', ts: Date.now() - 1000 * 60 * 60 * 48 },
    ],
    u2: [], u3: [], u4: [],
  },

  // ユーザー_コース の進捗
  progress: {
    // u1_c1 = { chaptersDone: [0,1,2,3,4], quizScores: {w5: 100, w1: 80} }
    u1_c1: { chaptersDone: [0, 1, 2, 3, 4], quizScores: { w1: 80, w5: 100 } },
    u1_c2: { chaptersDone: [0, 1], quizScores: {} },
    u3_c1: { chaptersDone: [0, 1, 2], quizScores: { w5: 75 } },
  },

  // お知らせ既読
  read: { u1: ['n2', 'n3', 'n4', 'n5'], u2: [], u3: [], u4: [] },
};
